version: '3.3'

services:
  postgres_db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres_db_vol:/var/lib/postgresql/data
    networks:
      connector:
        ipv4_address: 172.20.0.2

  python:
    container_name: python
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      connector:
        ipv4_address: 172.20.0.3


volumes:
  postgres_db_vol:


networks:
  connector:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16
        gateway: 172.20.0.1